version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-practice
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: training
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    image: php:8.2-apache
    container_name: php-practice
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  db_data:



